[package]
name = "ipcs-apidefs"
version = "0.0.0"
authors = ["Michal Hornicky <mhornick@redhat.com>"]
repository = ""
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "*", features = ["derive"] }
