[package]
name = "ipcs-cli"
version = "0.1.0"
authors = ["Michal Hornicky <mhornick@redhat.com>"]
edition = "2018"

[[bin]]
name = "ipcs"
path = "src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.clap]
version = "*"

[dependencies.ipcs-node]
path = "../node"

[dependencies.ipcs-api]
path = "../api"

[dependencies]
tokio = "0.2"
env_logger = "*"