[package]
name = "capitalize"
version = "0.1.0"
authors = ["Michal Hornicky <semtexzv@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies.ipcs]
package = "ipcs-runtime"
version = "0.0.1"

[dependencies]
