name: Build

on:
  push:
    branches: 
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all
        
